### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [zeroastro/zeroastro-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a LICENSE - if you haven't already decided on one,  I recommend [choosealicense.com](https://choosealicense.com).

**Comment by zeroastro** [comment]
The license has been added, here the commit:

https://github.com/zeroastro/zeroastro-zsh-theme/commit/eee100c94f6898aa70880fe087ef6e815553ecfc

Thanks you for opening the issue and for choosing my theme for your repo
